language: node_js
sudo: true
node_js: stable
script:
- npm run lint
- npm test
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: $CF_USERNAME
  password: $CF_PASSWORD
  organization: WatsonPlatformServices
  space: demos
  on:
    repo: watson-developer-cloud/document-conversion-nodejs
    branch: master
  skip_cleanup: true
notifications:
  email: false
